import type { Metadata } from "next";
import Link from "next/link";
import { pageMetadata, SITE_URL } from "@/lib/seo";
import { FIRMA } from "@/lib/firma";
import ContentLink from "@/components/wissen/ContentLink";
import PriceSheetExercise from "@/components/wissen/PriceSheetExercise";
import "./preisblatt.css";

const id = "excel-preisblatt-pruefen";
const path = `/wissen/${id}`;
const title = "Excel-Preisblatt prüfen: Checkliste für Gebäudereiniger";
const headline = "Excel-Preisblatt für Reinigungsausschreibungen prüfen: 7 Kontrollen vor der Abgabe";
const description = "Mengen, Einheiten, offene Preise und Formeln im Excel-Preisblatt prüfen. Mit fiktiver Fehlerübung, unabhängiger Gegenrechnung und druckbarem Prüfprotokoll.";
const base = pageMetadata(path, title, description);
const SOURCES = [
  { id: "excel_errors" as const, label: "Microsoft: Detect formula errors in Excel", url: "https://support.microsoft.com/en-us/excel/detect-formula-errors-in-excel", note: "Beschreibt Formelprüfung und typische Warnungen, etwa Zahlen als Text oder inkonsistente Formeln. Eine Warnung ist ein Prüfhinweis; eine fehlende Warnung belegt keine fachlich richtige Kalkulation." },
  { id: "excel_recalculation" as const, label: "Microsoft: Change formula recalculation, iteration, or precision in Excel", url: "https://support.microsoft.com/en-us/excel/change-formula-recalculation-iteration-or-precision-in-excel", note: "Erläutert Berechnungsmodus und Genauigkeit. Die Einstellung zur Genauigkeit wie angezeigt kann gespeicherte Werte dauerhaft verändern. Sie ist kein pauschales Reparaturmittel für Rundungsdifferenzen." },
];
export const metadata: Metadata = { ...base, robots: { index: false, follow: true }, authors: [{ name: "MerKalku", url: `${SITE_URL}/impressum` }], openGraph: { ...base.openGraph, type: "article" } };
const SECTIONS = [
  ["original", "Original & Version"], ["einheiten", "Mengen & Einheiten"], ["offene-preise", "Offene Preise"], ["formeln", "Formeln & Bereiche"], ["gegenrechnung", "Gegenrechnung"], ["neuberechnung", "Neuberechnung"], ["abgabedatei", "Abgabedatei"], ["uebung", "Fehlerübung"], ["pruefprotokoll", "Ihr Prüfprotokoll"], ["quellen", "Quellen"],
];
export default function PriceSheetArticle() {
  const graph = { "@context": "https://schema.org", "@graph": [
    { "@type": "Article", headline, description, mainEntityOfPage: `${SITE_URL}${path}`, author: { "@type": "Organization", name: "MerKalku", url: SITE_URL }, publisher: { "@type": "Organization", name: "MerKalku", url: SITE_URL }, inLanguage: "de-DE", citation: SOURCES.map(s => s.url) },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "MerKalku", item: SITE_URL }, { "@type": "ListItem", position: 2, name: "Wissen", item: `${SITE_URL}/wissen` }, { "@type": "ListItem", position: 3, name: "Excel-Preisblatt prüfen", item: `${SITE_URL}${path}` }] },
  ] };
  return <main className="knowledge-article price-article">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(graph).replace(/</g, "\\u003c") }} />
    <div className="article-intro knowledge-screen-only">
      <nav className="knowledge-breadcrumb" aria-label="Brotkrumennavigation"><Link href="/">MerKalku</Link><span>/</span><Link href="/wissen">Wissen</Link><span>/</span><span>Excel-Preisblatt prüfen</span></nav>
      <p className="knowledge-eyebrow">Angebotsprüfung · Arbeitshilfe 03</p>
      <h1>{headline}</h1>
      <p className="knowledge-lead">Eine fehlerfreie Formel kann den falschen Preis liefern. Prüfen Sie deshalb zuerst den Leistungsbezug – und erst dann das Excel-Ergebnis.</p>
      <div className="article-meta"><span>Von MerKalku</span><span>Inhaltsstand: 3. Oktober 2026</span><span className="price-draft">Vorschau · noch nicht veröffentlicht</span></div>
      <a className="btn-primary knowledge-button" href="#uebung">Fehler im Beispiel entdecken <span aria-hidden="true">↓</span></a>
    </div>
    <div className="knowledge-print-only print-heading"><p>MerKalku Wissen · Entwurf vom 03.10.2026</p><h1>Excel-Preisblatt prüfen</h1><p>Eigene organisatorische Arbeitshilfe. Beispielzahlen sind fiktiv; maßgeblich bleiben die konkreten Vergabeunterlagen.</p></div>
    <div className="article-grid"><aside className="article-toc knowledge-screen-only"><nav aria-label="In diesem Artikel"><p>In diesem Artikel</p>{SECTIONS.map(([anchor,label]) => <a key={anchor} href={`#${anchor}`}>{label}</a>)}</nav></aside><div className="article-body">
      <section className="article-answer knowledge-screen-only"><h2>Wie prüfe ich ein Excel-Preisblatt vor der Abgabe?</h2><p><strong>Gleichen Sie Version, Leistungsumfang, Mengen und Zeiteinheiten mit den Originalunterlagen ab. Klären Sie offene Preise, prüfen Sie Formelbereiche und rechnen Sie die wesentlichen Positionen unabhängig nach.</strong> Berechnen Sie anschließend in der vorgesehenen Excel-Umgebung neu und öffnen Sie genau die gespeicherte Abgabedatei erneut.</p><p>Diese sieben Kontrollen verbinden die Sicht des Kalkulators mit der Freigabe durch Inhaber oder Geschäftsführung. Sie ersetzen weder die Prüfung der konkreten Vergabeanforderungen noch eine belastbare Kostenkalkulation.</p></section>
      <section id="original" className="prose-section knowledge-screen-only"><h2>1. Arbeite ich im richtigen Original und darf ich diese Zellen ändern?</h2><p>Sichern Sie das unveränderte Ausgangsdokument. Notieren Sie Downloadstand, Dateiname und eventuelle Nachträge. Prüfen Sie in den Verfahrensunterlagen, welches Dateiformat abzugeben ist und welche Felder Sie ausfüllen dürfen. Eine ältere lokale Kopie kann trotz korrekter Rechnung unbrauchbar sein.</p><p><strong>Für den Kalkulator:</strong> Arbeiten Sie in einer eindeutig benannten Kopie. Prüfen Sie sichtbare Blätter, ausgeblendete Bereiche und Verweise, soweit die Datei dies erlaubt. Umgehen Sie keinen Schutz und ersetzen Sie vorgegebene Formeln nicht stillschweigend.</p><p><strong>Für die Geschäftsführung:</strong> Lassen Sie sich Originalstand, Arbeitsdatei und offene Rückfragen nennen. „Die Excel-Datei ist fertig“ ist noch keine nachvollziehbare Freigabe.</p><p className="article-takeaway">Beleg: Originalversion + zulässiges Abgabeformat + dokumentierte Abweichungen.</p></section>
      <section id="einheiten" className="prose-section knowledge-screen-only"><h2>2. Passen Menge, Einheit und Zeitraum zur Leistung?</h2><p>Lesen Sie jede wichtige Position als Satz: „Wie oft erbringen wir welche Leistung, in welchem Zeitraum und zu welchem Preis je Einheit?“ Bei einer Position mit zwölf Monaten bedeutet ein Einzelpreis etwas anderes als bei zwei Glasreinigungsterminen. Eine Flächenangabe allein sagt noch nicht, wie viele Reinigungen enthalten sind.</p><div className="fictional-example"><p className="fictional-label">Fiktives Beispiel</p><p>Zwölf Monate Büroreinigung × 800 € pro Monat = 9.600 € netto. Zwei Glasreinigungstermine × 450 € pro Termin = 900 € netto. Die zwei Termine dürfen nicht allein deshalb zu zwölf werden, weil die Vertragsdauer zwölf Monate beträgt.</p></div><p>Prüfen Sie außerdem Teilflächen, Lose, Grund- und Bedarfsleistungen sowie vereinbarte Rundungsregeln. Jahres-, Monats- und Vertragswerte dürfen erst nach einer ausdrücklich nachvollziehbaren Umrechnung verglichen werden.</p><p className="article-takeaway">Beleg: Fundstelle für Menge, Einheit, Häufigkeit und Bezugszeitraum je wesentlicher Position.</p></section>
      <section id="offene-preise" className="prose-section knowledge-screen-only"><h2>3. Ist ein Preis bewusst null – oder fehlt er?</h2><p>Ein leeres Feld ist keine kalkulierte Null. Je nach Formel kann Excel leere Werte bei einer Summe unauffällig übergehen. Die angezeigte Zahl ist dann nur eine Teilsumme. Trennen Sie deshalb „noch offen“, „bewusst mit null angesetzt“ und „nicht zutreffend“.</p><p>Welche Eingabe im konkreten Preisblatt zulässig ist, ergibt sich aus dessen Vorgaben. Tragen Sie kein erfundenes Ersatzzeichen und keinen Nullpreis ein, nur um eine Vollständigkeitsprüfung zu bestehen. Ein unklarer Leistungsumfang muss zuerst geklärt werden.</p><p className="article-takeaway">Beleg: Jede geforderte Preisposition ist bepreist oder ihre Behandlung wurde anhand der Vorgaben geklärt.</p></section>
      <section id="formeln" className="prose-section knowledge-screen-only"><h2>4. Rechnen die Formeln die richtigen Zellen zusammen?</h2><p>Prüfen Sie die Formel selbst und nicht nur den angezeigten Wert: Endet der Summenbereich vor der letzten Position? Verweist eine kopierte Zeile auf die vorherige Position? Wurde eine Formel durch eine feste Zahl ersetzt? Sind als Zahlen aussehende Inhalte tatsächlich Text?</p><p>Vergleichen Sie benachbarte Formeln, kontrollieren Sie Fehlermeldungen und verfolgen Sie relevante Zellbezüge. Beziehen Sie sichtbare und – soweit zugänglich – ausgeblendete Zeilen und Blätter ein. Die bloße Darstellung einer Zeile entscheidet nicht, ob sie in einer Formel enthalten ist.</p><aside className="article-source-note"><p>Microsoft beschreibt die Formelprüfung und ihre Warnungen. Sie findet bestimmte Auffälligkeiten, erkennt aber nicht, ob zwölf statt zwei Glasreinigungstermine fachlich falsch sind.</p><ContentLink contentId={id} kind="source" sourceId="excel_errors" href={SOURCES[0].url}>Microsoft: Formelprüfung ↗</ContentLink></aside><p className="article-takeaway">Beleg: Kontrollierte Formeln und Bereiche mit Blatt- und Zellangabe. Auffälligkeiten vor einer Änderung klären.</p></section>
      <section id="gegenrechnung" className="prose-section knowledge-screen-only"><h2>5. Komme ich unabhängig auf denselben Betrag?</h2><p>Rechnen Sie die wesentlichen Positionen aus Menge und Einzelpreis in einer eigenen Kontrollrechnung nach. Dieselbe Summenzelle noch einmal zu kopieren ist keine unabhängige Gegenrechnung. Stellen Sie sicher, dass beide Ergebnisse denselben Leistungsumfang, Zeitraum und Umsatzsteuerbezug haben.</p><p><strong>Aus Sicht der Geschäftsführung reicht der richtige Umsatz nicht:</strong> Passen die zugrunde gelegten Arbeitsstunden, Personalkosten und weiteren Kosten zu Ihrer betrieblichen Kalkulation? Können die Leistungen in den vorgesehenen Zeitfenstern erbracht werden? Ein vollständig bepreistes Angebot kann wirtschaftlich trotzdem untragbar sein.</p><p>Für die Stundenbasis hilft unser <Link href="/wissen/reinigungszeit-berechnen">Reinigungszeit-Rechner mit getrennten Raumgruppen und Zusatzzeiten</Link>. Die dort ermittelten Arbeitsstunden sind noch kein fertiger Personalplan.</p><p className="article-takeaway">Beleg: Eigene Gegenrechnung auf gleicher Basis + dokumentierte wirtschaftliche Annahmen.</p></section>
      <section id="neuberechnung" className="prose-section knowledge-screen-only"><h2>6. Wurde die Arbeitsmappe tatsächlich neu berechnet?</h2><p>Prüfen Sie den Berechnungsmodus und berechnen Sie die Datei in der vorgesehenen Excel-Version neu. Kontrollieren Sie danach Summen und Fehlermeldungen. Ein zuvor gespeicherter Ergebnisstand belegt nicht, dass spätere Eingaben bereits berücksichtigt sind.</p><p>Eine gezielte Änderung in Ihrer eigenen Testkopie kann helfen: Wenn zwei Termine jeweils um 50 € teurer werden, muss sich die entsprechende Summe um 100 € erhöhen. Übertragen Sie keine Teständerung versehentlich in die Abgabedatei.</p><p>Aktivieren Sie Makros oder externe Inhalte nicht ungeprüft. Klären Sie benötigte Verknüpfungen und die vorgesehene Arbeitsumgebung. Verändern Sie auch nicht pauschal die Einstellung „Genauigkeit wie angezeigt“: Microsoft weist darauf hin, dass dies gespeicherte Werte dauerhaft verändern kann.</p><aside className="article-source-note"><ContentLink contentId={id} kind="source" sourceId="excel_recalculation" href={SOURCES[1].url}>Microsoft: Neuberechnung und Genauigkeit ↗</ContentLink></aside><p className="article-takeaway">Beleg: Verwendete Excel-Version, ausgeführte Neuberechnung und kontrolliertes Ergebnis.</p></section>
      <section id="abgabedatei" className="prose-section knowledge-screen-only"><h2>7. Ist genau die gespeicherte Abgabedatei geprüft?</h2><p>Speichern, schließen und öffnen Sie die endgültige Datei erneut. Kontrollieren Sie Dateiname, Format, Pflichtfelder, relevante Summen und verbleibende Warnungen. Ein Screenshot aus einer anderen Arbeitskopie belegt den Zustand dieser Datei nicht.</p><p>Geben Sie dem internen Freigebenden den exakten Dateinamen, das Prüfprotokoll und die offenen Punkte. Die Upload- und Abgabeprüfung im Vergabeportal ist anschließend ein eigener Schritt. Weder dieses Arbeitsblatt noch sieben gesetzte Häkchen garantieren eine zulässige oder erfolgreiche Abgabe.</p><p className="article-takeaway">Beleg: Erneut geöffnete Enddatei + klar benannte Freigabeverantwortung + geklärte offene Punkte.</p></section>
      <PriceSheetExercise />
      <section id="quellen" className="article-sources knowledge-screen-only"><h2>Quellen und Grenzen dieser Arbeitshilfe</h2><p>Die Prüfstruktur, Beispielzahlen und Übung sind von MerKalku. Die Microsoft-Dokumentation stützt die technischen Hinweise zu Excel; sie bestätigt weder Beispielpreise noch Vergabeanforderungen.</p>{SOURCES.map(source => <div key={source.id}><h3><ContentLink contentId={id} kind="source" sourceId={source.id} href={source.url}>{source.label} ↗</ContentLink></h3><p>{source.note}</p></div>)}<p>Es wird keine echte Arbeitsmappe analysiert. Die vier Zustände zeigen Rechen- und Prüfprinzipien; ein Excel-spezifischer Fehler mit zwischengespeicherten Ergebnissen wird hier nicht technisch nachgestellt.</p></section>
      <nav className="price-related knowledge-screen-only" aria-label="Weitere Arbeitshilfen"><Link href="/wissen/ausschreibung-gebaeudereinigung-pruefen">← Zuerst den Umfang der Ausschreibung prüfen</Link><Link href="/wissen/reinigungszeit-berechnen">Arbeitsstunden mit eigenen Werten berechnen →</Link></nav>
      <section className="article-product knowledge-screen-only"><p className="knowledge-eyebrow">Vom Preisblatt zur Angebotsarbeit</p><h2>Weniger Übertragen. Mehr Zeit zum Prüfen.</h2><p>Sehen Sie sich an, wie MerKalku Sie bei der Kalkulation von Reinigungsausschreibungen unterstützt – und prüfen Sie im Gespräch, ob die Arbeitsweise zu Ihren Unterlagen passt.</p><ContentLink contentId={id} kind="product" href="/" className="btn-primary knowledge-button">MerKalku kennenlernen <span aria-hidden="true">↗</span></ContentLink></section>
      <footer className="article-editorial"><h2>Redaktion & Korrekturen</h2><p>Herausgeber: {FIRMA.marke} / {FIRMA.name}. Redaktioneller Kontakt: {FIRMA.geschaeftsfuehrer}, <a href={`mailto:${FIRMA.email}`}>{FIRMA.email}</a>.</p><p>Mit KI-Unterstützung erstellt. Inhaltsstand: 03.10.2026. Vorschau zur fachlichen Prüfung; noch nicht veröffentlicht. Die konkreten Verfahrensunterlagen und Ihre eigene Kalkulation bleiben maßgeblich.</p></footer>
    </div></div>
  </main>;
}
